### ISSUE TITLE
What's improved

### ISSUE THREAD

**Issue by liufeiluo** [lzhxmu/AccDiffusion_v2#1]
Hello, your work is very good, I would like to ask what has been improved in V2 and if there is a paper to refer to

**Comment by liufeiluo** [comment]
Are there any other improvements besides the addition of controlnet? Thank you for your help.

**Comment by lzhxmu** [comment]
> Are there any other improvements besides the addition of controlnet? Thank you for your help.

Thank you for your attention to our work. The paper will be released after the review is completed. Accdiffusion v2 introduces controllable generation such as controlnet to make high-resolution local structures more controllable. Please look forward to our final paper version. Thanks！
